CREATE TABLE sites (
    # The bread and butter
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    # The meat
    host VARCHAR(255) NOT NULL UNIQUE,
    webhook_secret VARCHAR(64) NOT NULL UNIQUE
);
