ALTER TABLE posts ADD COLUMN `sensitive` BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE posts ADD COLUMN content_warning VARCHAR(500) NULL DEFAULT NULL;
ALTER TABLE users ADD COLUMN show_sensitive_media BOOLEAN DEFAULT FALSE NOT NULL;
