services:
  mysql-test:
    image: mysql:8.4.8@sha256:669b2d89f3916f5263af230ffa20889a03c7f4bedf58133fe8780466c613f7ae
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reconcile-account-topics
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
