services:
  mysql-test:
    image: mysql:8.4.10@sha256:c592c15aaf4a1961e15d82eb31ea5987dda862d1c4b1e93424438c0e91dc1f8d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reconcile-account-topics
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
