services:
  mysql-test:
    image: mysql:8.4.9@sha256:6e54d72c66fb55fa2bba384cba8c7c0ea9d629fb4d2af613b0eef98d19c6df15
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reconcile-account-topics
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
