-- Generated by `pnpm schema:dump` from migrations up to 83
-- For reference only. It is not applied to any database.
-- Do not edit by hand, add a migration instead.

CREATE TABLE `account_aliases` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `account_id` int unsigned NOT NULL,
  `ap_id` varchar(1024) NOT NULL,
  `ap_id_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(`ap_id`,256))) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_alias` (`account_id`,`ap_id_hash`),
  KEY `idx_account_aliases_ap_id_hash` (`ap_id_hash`),
  CONSTRAINT `account_aliases_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `account_delivery_backoffs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `account_id` int unsigned NOT NULL,
  `last_failure_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `last_failure_reason` text,
  `backoff_until` timestamp(6) NOT NULL,
  `backoff_seconds` int unsigned NOT NULL DEFAULT '60',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_account_delivery_backoffs_account` (`account_id`),
  KEY `idx_account_delivery_backoffs_backoff` (`backoff_until`),
  CONSTRAINT `fk_account_delivery_backoffs_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `account_topics` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int unsigned NOT NULL,
  `topic_id` int unsigned NOT NULL,
  `rank_in_topic` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_account_topic` (`account_id`,`topic_id`),
  KEY `idx_account_topics_topic_id_rank_in_topic` (`topic_id`,`rank_in_topic`),
  CONSTRAINT `account_topics_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `account_topics_ibfk_2` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `accounts` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `username` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `bio` text,
  `avatar_url` varchar(1024) DEFAULT NULL,
  `banner_image_url` varchar(1024) DEFAULT NULL,
  `url` varchar(1024) DEFAULT NULL,
  `custom_fields` json DEFAULT NULL,
  `ap_id` varchar(1024) NOT NULL,
  `ap_inbox_url` varchar(1024) NOT NULL,
  `ap_shared_inbox_url` varchar(1024) DEFAULT NULL,
  `ap_public_key` text,
  `ap_private_key` text,
  `ap_outbox_url` varchar(1024) DEFAULT NULL,
  `ap_following_url` varchar(1024) DEFAULT NULL,
  `ap_followers_url` varchar(1024) DEFAULT NULL,
  `ap_liked_url` varchar(1024) DEFAULT NULL,
  `uuid` char(36) DEFAULT NULL,
  `ap_id_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(`ap_id`,256))) STORED,
  `domain` varchar(255) NOT NULL,
  `domain_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(lower(`domain`),256))) STORED,
  `ap_inbox_url_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(lower(`ap_inbox_url`),256))) STORED,
  `webfinger_host` varchar(255) DEFAULT NULL,
  `webfinger_host_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(lower(`webfinger_host`),256))) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `idx_ap_id_hash` (`ap_id_hash`),
  UNIQUE KEY `idx_accounts_username_webfinger_host_hash` (`username`,`webfinger_host_hash`),
  KEY `idx_accounts_username` (`username`),
  KEY `idx_accounts_domain_hash` (`domain_hash`),
  KEY `idx_accounts_ap_inbox_url_hash` (`ap_inbox_url_hash`),
  KEY `idx_accounts_webfinger_host_hash` (`webfinger_host_hash`),
  FULLTEXT KEY `idx_accounts_fulltext_search` (`name`,`username`,`domain`,`webfinger_host`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `blocks` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `blocker_id` int unsigned NOT NULL,
  `blocked_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_blocker_blocked` (`blocker_id`,`blocked_id`),
  KEY `idx_blocks_blocked_id_blocker_id` (`blocked_id`,`blocker_id`),
  CONSTRAINT `blocks_ibfk_1` FOREIGN KEY (`blocker_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `blocks_ibfk_2` FOREIGN KEY (`blocked_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `bluesky_integration_account_handles` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `account_id` int unsigned NOT NULL,
  `handle` varchar(255) DEFAULT NULL,
  `confirmed` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_bluesky_integration_account_handles_account` (`account_id`),
  UNIQUE KEY `idx_bluesky_integration_account_handles_handle` (`handle`),
  CONSTRAINT `fk_bluesky_integration_account_handles_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `discovery_feeds` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `post_type` tinyint unsigned DEFAULT NULL,
  `published_at` timestamp(6) NOT NULL,
  `topic_id` int unsigned NOT NULL,
  `post_id` int unsigned NOT NULL,
  `author_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `post_id` (`post_id`),
  KEY `author_id` (`author_id`),
  KEY `idx_discovery_feeds_post_type` (`post_type`),
  KEY `idx_discovery_feeds_published_at` (`published_at`),
  KEY `idx_discovery_feeds_topic_id` (`topic_id`),
  CONSTRAINT `discovery_feeds_ibfk_1` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON DELETE CASCADE,
  CONSTRAINT `discovery_feeds_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `discovery_feeds_ibfk_3` FOREIGN KEY (`author_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `domain_blocks` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `blocker_id` int unsigned NOT NULL,
  `domain` varchar(255) NOT NULL,
  `domain_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(lower(`domain`),256))) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_blocker_domain` (`blocker_id`,`domain`),
  UNIQUE KEY `unique_blocker_domain_hash` (`blocker_id`,`domain_hash`),
  KEY `idx_domain_blocks_domain_hash` (`domain_hash`),
  CONSTRAINT `domain_blocks_ibfk_1` FOREIGN KEY (`blocker_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `feeds` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `post_type` tinyint unsigned DEFAULT NULL,
  `audience` tinyint unsigned DEFAULT NULL,
  `user_id` int unsigned NOT NULL,
  `post_id` int unsigned NOT NULL,
  `author_id` int unsigned NOT NULL,
  `reposted_by_id` int unsigned DEFAULT NULL,
  `published_at` timestamp(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_feeds_user_post` (`user_id`,`post_id`,`reposted_by_id`),
  KEY `post_id` (`post_id`),
  KEY `author_id` (`author_id`),
  KEY `reposted_by_id` (`reposted_by_id`),
  KEY `idx_feeds_user_id_post_type` (`user_id`,`post_type`,`published_at` DESC),
  CONSTRAINT `feeds_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `feeds_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `feeds_ibfk_3` FOREIGN KEY (`author_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `feeds_ibfk_4` FOREIGN KEY (`reposted_by_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `follows` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `follower_id` int unsigned NOT NULL,
  `following_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_follower_following` (`follower_id`,`following_id`),
  KEY `idx_follows_follower_id_following_id` (`follower_id`,`following_id`),
  KEY `idx_follows_following_id_follower_id` (`following_id`,`follower_id`),
  KEY `idx_following_id` (`following_id`),
  KEY `idx_follower_id` (`follower_id`),
  CONSTRAINT `follows_ibfk_1` FOREIGN KEY (`follower_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `follows_ibfk_2` FOREIGN KEY (`following_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ghost_ap_post_mappings` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `ghost_uuid` char(36) NOT NULL,
  `ap_id` varchar(1024) NOT NULL,
  `ap_id_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(`ap_id`,256))) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ghost_uuid` (`ghost_uuid`),
  UNIQUE KEY `ap_id_hash` (`ap_id_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `key_value` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(768) DEFAULT NULL,
  `value` json NOT NULL,
  `expires` datetime DEFAULT NULL,
  `object_id` varchar(255) GENERATED ALWAYS AS (left(json_unquote(json_unquote(json_extract(`value`,_utf8mb4'$.object.id'))),255)) STORED,
  `object_in_reply_to` varchar(255) GENERATED ALWAYS AS (left(json_unquote(json_unquote(json_extract(`value`,_utf8mb4'$.object.inReplyTo'))),255)) STORED,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `object` varchar(255) GENERATED ALWAYS AS ((case when regexp_like(json_unquote(json_unquote(json_extract(`value`,_utf8mb4'$.object'))),_utf8mb4'^https') then left(json_unquote(json_unquote(json_extract(`value`,_utf8mb4'$.object'))),255) else _utf8mb4'' end)) STORED,
  `json_id` varchar(255) GENERATED ALWAYS AS ((case when regexp_like(json_unquote(json_unquote(json_extract(`value`,_utf8mb4'$.id'))),_utf8mb4'^https') then left(json_unquote(json_unquote(json_extract(`value`,_utf8mb4'$.id'))),255) else _utf8mb4'' end)) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`key`),
  KEY `idx_object_id` (`object_id`),
  KEY `idx_object_in_reply_to` (`object_in_reply_to`),
  KEY `idx_object` (`object`),
  KEY `idx_json_id` (`json_id`),
  KEY `idx_expires` (`expires`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `likes` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `account_id` int unsigned NOT NULL,
  `post_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_id` (`account_id`,`post_id`),
  KEY `post_id` (`post_id`),
  CONSTRAINT `likes_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `likes_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mentions` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `post_id` int unsigned NOT NULL,
  `account_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_account_post` (`account_id`,`post_id`),
  KEY `post_id` (`post_id`),
  CONSTRAINT `mentions_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `mentions_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notifications` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `event_type` tinyint unsigned NOT NULL,
  `user_id` int unsigned NOT NULL,
  `account_id` int unsigned NOT NULL,
  `post_id` int unsigned DEFAULT NULL,
  `in_reply_to_post_id` int unsigned DEFAULT NULL,
  `read` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`),
  KEY `post_id` (`post_id`),
  KEY `in_reply_to_post_id` (`in_reply_to_post_id`),
  KEY `idx_notifications_user_id` (`user_id`,`id` DESC),
  KEY `idx_notifications_user_id_read` (`user_id`,`read`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notifications_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notifications_ibfk_3` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `notifications_ibfk_4` FOREIGN KEY (`in_reply_to_post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `outboxes` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL DEFAULT (uuid()),
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `published_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `post_type` tinyint unsigned NOT NULL,
  `outbox_type` tinyint unsigned NOT NULL,
  `account_id` int unsigned NOT NULL,
  `post_id` int unsigned NOT NULL,
  `author_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `uniq_outboxes_account_post_outbox_type` (`account_id`,`post_id`,`outbox_type`),
  KEY `post_id` (`post_id`),
  KEY `author_id` (`author_id`),
  KEY `idx_outboxes_account_id_outbox_type_published_at_desc` (`account_id`,`outbox_type`,`published_at` DESC),
  CONSTRAINT `outboxes_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `outboxes_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `outboxes_ibfk_3` FOREIGN KEY (`author_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `posts` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` char(36) NOT NULL DEFAULT (uuid()),
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `type` tinyint unsigned NOT NULL,
  `audience` tinyint unsigned NOT NULL,
  `author_id` int unsigned NOT NULL,
  `title` varchar(256) DEFAULT NULL,
  `excerpt` varchar(500) DEFAULT NULL,
  `content` longtext,
  `url` varchar(1024) NOT NULL,
  `image_url` varchar(2000) DEFAULT NULL,
  `published_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `like_count` int unsigned NOT NULL DEFAULT '0',
  `repost_count` int unsigned NOT NULL DEFAULT '0',
  `reply_count` int unsigned NOT NULL DEFAULT '0',
  `reading_time_minutes` int unsigned NOT NULL DEFAULT '0',
  `ap_id` varchar(1024) NOT NULL,
  `ap_id_hash` binary(32) GENERATED ALWAYS AS (unhex(sha2(`ap_id`,256))) STORED,
  `in_reply_to` int unsigned DEFAULT NULL,
  `thread_root` int unsigned DEFAULT NULL,
  `attachments` json DEFAULT NULL,
  `deleted_at` timestamp(6) NULL DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `summary` varchar(500) DEFAULT NULL,
  `sensitive` tinyint(1) NOT NULL DEFAULT '0',
  `content_warning` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `ap_id_hash` (`ap_id_hash`),
  KEY `author_id` (`author_id`),
  KEY `in_reply_to` (`in_reply_to`),
  KEY `thread_root` (`thread_root`),
  KEY `idx_posts_type_author` (`type`,`author_id`,`id`),
  CONSTRAINT `posts_ibfk_1` FOREIGN KEY (`author_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `posts_ibfk_2` FOREIGN KEY (`in_reply_to`) REFERENCES `posts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `posts_ibfk_3` FOREIGN KEY (`thread_root`) REFERENCES `posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `reposts` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `account_id` int unsigned NOT NULL,
  `post_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `account_id` (`account_id`,`post_id`),
  KEY `post_id` (`post_id`),
  CONSTRAINT `reposts_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reposts_ibfk_2` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `sites` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `host` varchar(255) NOT NULL,
  `webhook_secret` varchar(64) NOT NULL,
  `ghost_pro` tinyint(1) NOT NULL DEFAULT '1',
  `ghost_uuid` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `host` (`host`),
  UNIQUE KEY `webhook_secret` (`webhook_secret`),
  UNIQUE KEY `ghost_uuid` (`ghost_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `topics` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `display_order` int unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `account_id` int unsigned NOT NULL,
  `site_id` int unsigned NOT NULL,
  `show_sensitive_media` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`),
  KEY `site_id` (`site_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `users_ibfk_2` FOREIGN KEY (`site_id`) REFERENCES `sites` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

