#!/bin/sh
set -e

PORT=${MYSQL_PORT:-3306}

if [ -n "$MYSQL_SOCKET_PATH" ]; then
  echo "Using Unix socket for $MYSQL_SOCKET_PATH"
  SOCKET="--socket=$MYSQL_SOCKET_PATH"
  HOSTPORT=""
else
  echo "Using TCP host $MYSQL_HOST:$PORT"
  SOCKET=""
  HOSTPORT="--host=$MYSQL_HOST --port=$PORT"
fi

mysql $SOCKET $HOSTPORT -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" -e \
  "DELETE FROM key_value WHERE expires IS NOT NULL AND expires < UTC_TIMESTAMP();"