const SCALING_FACTOR = 1;

const NUM_SITES = 60_000 * SCALING_FACTOR;
const NUM_USERS = 300_000 * SCALING_FACTOR;
const NUM_ACCOUNTS = 2_500_000 * SCALING_FACTOR;
const NUM_POSTS = 3_000_000 * SCALING_FACTOR;

module.exports = {
    SCALING_FACTOR,
    NUM_SITES,
    NUM_USERS,
    NUM_ACCOUNTS,
    NUM_POSTS,
};
