services:
  mysql-test:
    image: mysql:8.4.10@sha256:c831a0f11348d402b43d77453e17d770be2eef356615a2823fe0f5a0d6c8b9af
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: __JOB_NAME__
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
