services:
  mysql-test:
    image: mysql:8.4.10@sha256:563602a18ffd5be220968e8508d84c9dcd80fbffe69e28af51572db29e3285b2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: __JOB_NAME__
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
