services:
  mysql-test:
    image: mysql:8.4.11@sha256:85b9bf2e29cf836ecb8c2a15a935d4ba0c606631dff1dd79531a11983c638f2a
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: __JOB_NAME__
    ports:
      - "3308:3306"
    tmpfs:
      - /var/lib/mysql
